/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mohmor.gephi.EfficiencyAttack;

/**
 *
 * @author mohsen
 */
public class EfficiencyAttackPanel extends javax.swing.JPanel {

    /**
     * Creates new form EfficiencyAttackPanel
     */
    public EfficiencyAttackPanel() {
        initComponents();
    }

    
    public boolean[] GetIsEnabledAttacks()
    {
        boolean[] _result = new boolean[4];
        _result[0] = jCheckBox1.isSelected();
        _result[1] = jCheckBox2.isSelected();
        _result[2] = jCheckBox3.isSelected();
        _result[3] = jCheckBox4.isSelected();
        
        return _result;
        
    }
    
    public float GetScaleX()
    {
        return ((int) txtbNum_scaleX.getValue()) * 1.0f;
        
    }
    
    public float GetScaleY()
    {
        return ((int) txtbNum_scaleY.getValue() )* 1.0f;
        
    }
    
    public int GetRemoveCountPerStep()
    {
        return ((int) txtbNum_stepRemove.getValue() );
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        txtbNum_scaleX = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        txtbNum_scaleY = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        txtbNum_stepRemove = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();

        jCheckBox1.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox1, org.openide.util.NbBundle.getMessage(EfficiencyAttackPanel.class, "EfficiencyAttackPanel.chb_IsEnableInitDegreeAttack.text")); // NOI18N
        jCheckBox1.setName("chb_IsEnableInitDegreeAttack"); // NOI18N

        jCheckBox2.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox2, org.openide.util.NbBundle.getMessage(EfficiencyAttackPanel.class, "EfficiencyAttackPanel.jCheckBox2.text")); // NOI18N
        jCheckBox2.setToolTipText(org.openide.util.NbBundle.getMessage(EfficiencyAttackPanel.class, "EfficiencyAttackPanel.jCheckBox2.toolTipText")); // NOI18N
        jCheckBox2.setName("chb_IsEnableRecalculateDegreeAttack"); // NOI18N

        jCheckBox3.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox3, org.openide.util.NbBundle.getMessage(EfficiencyAttackPanel.class, "EfficiencyAttackPanel.jCheckBox3.text")); // NOI18N
        jCheckBox3.setName("chb_IsEnableInitBetweennessAttack"); // NOI18N

        jCheckBox4.setSelected(true);
        jCheckBox4.setActionCommand(org.openide.util.NbBundle.getMessage(EfficiencyAttackPanel.class, "EfficiencyAttackPanel.jCheckBox4.actionCommand")); // NOI18N
        jCheckBox4.setLabel(org.openide.util.NbBundle.getMessage(EfficiencyAttackPanel.class, "EfficiencyAttackPanel.jCheckBox4.label")); // NOI18N
        jCheckBox4.setName("chb_IsEnablRecalculatetBetweennessAttack"); // NOI18N

        txtbNum_scaleX.setValue(10);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(EfficiencyAttackPanel.class, "EfficiencyAttackPanel.jLabel1.text")); // NOI18N
        jLabel1.setToolTipText(org.openide.util.NbBundle.getMessage(EfficiencyAttackPanel.class, "EfficiencyAttackPanel.jLabel1.toolTipText")); // NOI18N

        txtbNum_scaleY.setValue(500);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(EfficiencyAttackPanel.class, "EfficiencyAttackPanel.jLabel2.text")); // NOI18N
        jLabel2.setToolTipText(org.openide.util.NbBundle.getMessage(EfficiencyAttackPanel.class, "EfficiencyAttackPanel.jLabel2.toolTipText")); // NOI18N

        txtbNum_stepRemove.setValue(1);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(EfficiencyAttackPanel.class, "EfficiencyAttackPanel.jLabel3.text")); // NOI18N
        jLabel3.setToolTipText(org.openide.util.NbBundle.getMessage(EfficiencyAttackPanel.class, "EfficiencyAttackPanel.jLabel3.toolTipText")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtbNum_scaleX, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtbNum_stepRemove, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbNum_scaleY, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbNum_scaleX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbNum_scaleY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbNum_stepRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner txtbNum_scaleX;
    private javax.swing.JSpinner txtbNum_scaleY;
    private javax.swing.JSpinner txtbNum_stepRemove;
    // End of variables declaration//GEN-END:variables
}
